RMDIR /Q /S .\redis-1\logs
RMDIR /Q /S .\redis-1\master-data
RMDIR /Q /S .\redis-2\logs
RMDIR /Q /S .\redis-2\master-data
RMDIR /Q /S .\redis-3\logs
RMDIR /Q /S .\redis-3\master-data
RMDIR /Q /S .\redis-4\logs
RMDIR /Q /S .\redis-4\master-data
RMDIR /Q /S .\redis-5\logs
RMDIR /Q /S .\redis-5\master-data
RMDIR /Q /S .\redis-6\logs
RMDIR /Q /S .\redis-6\master-data