version: '3'
networks:
  redis-cluster:
    external: true
services:
  redis-4:
    image: redis:7.0.9
    container_name: redis-4
    privileged: true
    environment:
      TZ: Asia/Shanghai
    networks:
      - redis-cluster
    ports:
      - "6394:6394"
      - "16394:16394"
    volumes:
      - ./master-data:/data:rw
      - ./conf/redis.conf:/etc/redis/redis.conf:rw
      - ./logs:/var/log/redis:rw
    command: [ "redis-server","/etc/redis/redis.conf" ]