version: '3'
services:
  nexus3:
    image: sonatype/nexus3:3.66.0
    container_name: nexus3
    ports:
      - "8081:8081"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./sonatype/data:/nexus-data
      - ./sonatype/etc:/opt/sonatype/nexus/etc
      - ./sonatype/bin/nexus.vmoptions:/opt/sonatype/nexus/bin/nexus.vmoptions