RMDIR /Q /S .\redis-master-slave\redis-master-1\logs
RMDIR /Q /S .\redis-master-slave\redis-master-1\master-data
RMDIR /Q /S .\redis-master-slave\redis-slave-1\logs
RMDIR /Q /S .\redis-master-slave\redis-slave-1\master-data
RMDIR /Q /S .\redis-master-slave\redis-slave-2\logs
RMDIR /Q /S .\redis-master-slave\redis-slave-2\master-data
RMDIR /Q /S .\redis-sentinel\redis-sentinel-1\logs
RMDIR /Q /S .\redis-sentinel\redis-sentinel-2\logs
RMDIR /Q /S .\redis-sentinel\redis-sentinel-3\logs