version: '3'
networks:
  zookeeper-cluster:
    external: true
services:
  zookeeper-2:
    image: zookeeper:3.8.0
    container_name: zookeeper-2
    hostname: zookeeper-2
    networks:
      - zookeeper-cluster
    privileged: true
    volumes:
      - ./data:/data:rw
      - ./datalog:/datalog:rw
      - ./conf:/conf:rw
    ports:
      - "2182:2181"
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2